name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag matcodewarrior/microblog:v2.0.0
    #- name: Run Docker
    #  run: docker run --name microblog -dp 8000:5000 microblog
    - name: Docker Push
      run: docker push matcodewarrior/microblog:v2.0.0
